const cookie = [
    {
        "domain": ".auto.ru",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_csrf_token",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "049fe96e1fd6f8d5f8927a32cb86f175cfbee5577330b98c",
        "id": 1
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1581282143,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ym_wasSynced",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%7B%22time%22%3A1581178463736%2C%22params%22%3A%7B%22eu%22%3A1%7D%2C%22bkParams%22%3A%7B%7D%7D",
        "id": 2
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1612714462.009419,
        "hostOnly": false,
        "httpOnly": false,
        "name": "autoru_gdpr",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 3
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1582388060.544923,
        "hostOnly": false,
        "httpOnly": true,
        "name": "autoru_sid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "a%3Ag5e36bd272081cs8mati88flqtgq7fu9.423991ed5912e8b4d5c5428bef738fd9%7C1581250471264.604800.22DJOf5DG-07FKgazSY0Rg.Zzwh7Irw3BBdzfV_LLeiSK58yBHdy6ELIsgjg2A-lEY",
        "id": 4
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1581855271.322821,
        "hostOnly": false,
        "httpOnly": true,
        "name": "autoruuid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g5e36bd272081cs8mati88flqtgq7fu9.423991ed5912e8b4d5c5428bef738fd9",
        "id": 5
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1581250474,
        "hostOnly": false,
        "httpOnly": false,
        "name": "cmtchd",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "MTU4MDY0NTY3NDQzNw==",
        "id": 6
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1581855274,
        "hostOnly": false,
        "httpOnly": false,
        "name": "crookie",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "QPB+I4nxYbiIfNME/RvzX52gURgD8x1zs1ev2aIuynshJAS6q3fNbjdkS1XdGrdl7PStxqQpAoxTPahYF3c4SZURViw=",
        "id": 7
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1581861817,
        "hostOnly": false,
        "httpOnly": false,
        "name": "cycada",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "bdTnw2IO/SBHPw3sq5Q110vbrmlBIm581aMRZW08Pys=",
        "id": 8
    },
    {
        "domain": ".auto.ru",
        "hostOnly": false,
        "httpOnly": true,
        "name": "from",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "direct",
        "id": 9
    },
    {
        "domain": ".auto.ru",
        "hostOnly": false,
        "httpOnly": true,
        "name": "from_lifetime",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "1581178465144",
        "id": 10
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1612181673.421251,
        "hostOnly": false,
        "httpOnly": false,
        "name": "gdpr",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 11
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1612181673.519948,
        "hostOnly": false,
        "httpOnly": false,
        "name": "suid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "b7755aeec5fc4ee90446de8db5a132fc.d13f08e0cc0cb68246c9ab56682297a0",
        "id": 12
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1581182066.675886,
        "hostOnly": false,
        "httpOnly": false,
        "name": "X-Vertis-DC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "sas",
        "id": 13
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1583770463.582451,
        "hostOnly": false,
        "httpOnly": false,
        "name": "yandexuid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7937484891580978450",
        "id": 14
    }
];

export default cookie;